name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: workflowreg.azurecr.io,
          username: ${{ ACR_USERNAME }}
          password: ${{ ACR_PASSWORD }}

      - run: |
          docker login workflowreg.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
          docker build . -t workflowreg.azurecr.io/ghost:${{ github.sha }}
          docker push workflowreg.azurecr.io/ghost:${{ github.sha }}
